server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "mysql"
          host: temporalmysql.mysql.database.azure.com
          port: 3306
          database: temporal
          user: test
          password: Sree@1628888
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "mysql"
          host: temporalmysql.mysql.database.azure.com
          port: 3306
          database: temporal_visibility
          user: test
          password: Sree@1628888
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: true

postgresql:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
